add unzip

diff --git a/.github/workflows/nightly_build_2.yml b/.github/workflows/nightly_build_2.yml
--- a/.github/workflows/nightly_build_2.yml
+++ b/.github/workflows/nightly_build_2.yml
@@ -185,18 +185,28 @@ jobs:
             echo "🔍 Checking AWS CLI installation..."
             if ! command -v aws &> /dev/null; then
               echo "🚀 Installing AWS CLI..."
-              
+
+              if ! command -v unzip &> /dev/null; then
+                echo "📦 Installing unzip..."
+                sudo apt update -y
+                sudo apt install -y unzip
+              fi
+
               curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+
               unzip awscliv2.zip
               
               sudo ./aws/install
-              
+
               rm -rf awscliv2.zip aws
               
             else
               echo "✅ AWS CLI already installed."
             fi
-    
+            
+            echo "AWS CLI Version:"
+            aws --version || echo "❌ AWS CLI installation failed!"
+
             echo "Logging in to AWS ECR..."
             aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin $ECR_REGISTRY
 
